# Generated by Django 5.1.4 on 2024-12-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0002_alter_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
